# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://recon-gathering-March2018.netlify.com"
languageCode = "en-AU"
title = "RECON gathering"

# Metadata
[params]
  author = "Thibaut Jombart"
  description = "Event website for the RECON gathering, London, 22-23 March 2018"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/paddington-basin.jpg"
  title = "RECON gathering #1"
  description = "London, Paddington Basin, 22-23 March 2018"

# Navigation section
[params.nav]
  mission = "Practical info"
  services = "Programme"
  team = "Organisers"
  contact = "Register"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  # [params.mission.images]
  #   enable = true

  #   [[params.mission.images.list]]
  #     img = "images/compass.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/img_4.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/img_1.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/calendar.jpg"

  [[params.mission.item]]
    weight = 1
    name = "location"
    title = "Location"
    subtitle = 'The event will be hosted at the Novotel Paddington, in the middle of little venice, London'
    description = '<p>Here is a map of the campus:<br><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d4965.3659452534275!2d-0.182594!3d51.519032!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x6da98aa2acd4015f!2sHotel+Novotel+London+Paddington!5e0!3m2!1sen!2suk!4v1515162861305" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe></p>'

  [[params.mission.item]]
    weight = 2
    name = "date"
    title = "Date"
    subtitle = "The event will take place over 2 days, 22-23 March 2018"
    description = ""

  [[params.mission.item]]
    weight = 3
    name = "register"
    title = "Register"
    subtitle = "Please use the google form below to apply. Deadline for registration is 11th February 2018."
    description = '<p>Google form coming soon.</p>'
 
  [[params.mission.item]]
    weight = 4
    name = "contact"
    title = "Contact"
    subtitle = "For more information, use the contact provided below."
    description = "<p><ul><li>organisation: <a href='mailto:thibautjombart@gmail.com'>Thibaut Jombart</a></ul></p>"

  # [[params.mission.item]]
  #   weight = 5
  #   name = "scholarships"
  #   title = "Scholarships"
  #   subtitle = "If you need financial support for travel and accommodation to attend the course, you can apply to a scholarship for this course. See the relevant section in the registration form (see 'register' section)."
  #   description = ""



# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Programme"
  description = "The event will be running over 2 days, 22-23 March 2018. The first day will be a symposium giving an overview of the activities of our community, focussing on the role of modelling and analytics for informing outbreak response. The second day will consist in two parallel sessions, including a working group on field epidemiology training resources, and a community-driven hackathon. The entire event will be hosted in the <a href='https://www.accorhotels.com/gb/hotel-6455-novotel-london-paddington/index.shtml'>Novotel Paddington</a>"

  # [[params.services.item]]
  #   icon = "icon-present"
  #   title = "Web Development"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = ""
    title = "Registration"
    description = "<p><b>Thursday 22nd March 2018 <br>9:00 - 9:30</b></p><p>Welcoming the participants, coffee.</p>"

  [[params.services.item]]
    icon = ""
    title = "Symposium"
    description = "<p><b>Thursday 22nd March 2018 <br>9:30 - 17:00</b></p><p>The programme will be announced closer to the event</p>"

  [[params.services.item]]
    icon = ""
    title = "Social event"
    description = "<p><b>Thursday 22nd March 2018 <br> 17:30 - 23:00</b></p><p>Reception at the bar of the hotel, followed by dinner.</p>"

  [[params.services.item]]
    icon = ""
    title = "Parallel session 1"
    description = "<p><b>Friday 23rd March 2018 <br>9:30 - 16:00</b></p><p>Working group on resources for field epidemiology training.</p>"

  [[params.services.item]]
    icon = ""
    title = "Parallel session 2"
    description = "<p><b>Friday 23rd March 2018 <br>9:30 - 16:00</b></p><p>Community-driven hackathon. An online form will soon be published to suggest themes.</p>"

  [[params.services.item]]
    icon = ""
    title = "Conclusion"
    description = "<p><b>Friday 23rd March 2018 <br>16:00 - 16:30</b></p><p>Debriefing of parallel sessions and concluding remarks.</p>"

 

# # Work section
# [params.work]
#   enable = false

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_1.jpg"

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_2.jpg"

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_3.jpg"

# Team section
[params.team]
  enable = true
  title = "Organisers"
  description = ""

  [[params.team.item]]
    name = "Thibaut Jombart"
    position = "Lecturer, Imperial College London"
    description = "Genetic epidemiology and outbreak response. Head of the R Epidemics Consortium (RECON)."
    img = "images/thibaut.jpg"
    # dribbble = "#"
    github = "https://github.com/thibautjombart"
    twitter = "https://twitter.com/TeebzR"

  [[params.team.item]]
    name = "Amrish Baidjoe"
    position = "Research Associate, Imperial College London"
    description = "Field epidemiologist and core RECON member, president of the EPIET alumni network."
    img = "images/amrish.jpg"
    # facebook = "#"
    # twitter = "#"

  [[params.team.item]]
    name = "Susannah Fisher"
    position = "Senior Administrator, Imperial College London"
    description = "Administrator of the MRC Centre for Outbreak Analysis and Modelling, and logistics guru for the event."
    img = "images/susannah.jpg"
    # facebook = "#"
    # twitter = "#"
    # github = "#"

  # [[params.team.item]]
  #   name = "James Hayward"
  #   position = "Senior Administrator, Imperial College London"
  #   description = "Head administrator for the NIHR-HPRU, and logistics guru for the short course."
  #   img = "images/james.jpg"
  #   # facebook = "#"
  #   # twitter = "#"
  #   # github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = false
  title = "Register"
  message = "Bla bla bla"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>This event is co-funded by the Medical Research Council (MRC) Centre for Outbreak Analysis and Modelling, and the National Institute for Health Research - Health Protection Research Unit (NIHR-HPRU) for Modelling Methodology.</small></p><p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a> Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a>. Website by <a href='https://thibautjombart.netlify.com/'>Thibaut Jombart</a>.</small></p>"
  github = "https://github.com/reconhub/meeting-march-2018"
  
